const animais =[
    "Abelha", "ácaro", "água viva", "águia", "albatróz", "andorinha", "anêmona", "anta", "antílope", 
    "aranha", "arara", "atum", "avestruz", "azulão", "baiacu", "baleia", "barata", "bem te vi", "besouro", 
    "bezerro", "bicho da seda", "bicho pau", "biguá", "bode", "boi", "borboleta", "boto", "bruxinha", "Bufalo", 
    "burro", "cabra", "cacatua", "cachorro", "cágado", "calopsita", "camarão", "camaleão", "camelo", "canário", 
    "canguru", "caracol", "caramujo", "caravela", "carcará", "carneiro", "carpa", "castor", "cavalo", 
    "cavalo marinho", "chimpanzé", "chinchila", "cigarra", "cisne", "centopéia", "cervo", "coala", "cobra", 
    "codorna", "coelho", "coiote", "coleiro", "coral", "coruja", "coruja buraqueira", "cordeiro", "corvo", 
    "cotia", "craca", "crocodilo", "cupim", "curió", "diabo da tasmânia", "dinossauro", "dragão barbudo", 
    "dragão de Komodo", "dragão do brejo", "dromedário", "elefante", "ema", "enguia", "equidna", "escorpião", 
    "esponja do mar", "esquilo", "estrela do mar", "faisão", "falcão", "ferrete", "flamingo", "foca", "formiga", 
    "furão", "gaivota", "galinha", "galo", "gambá", "gato", "gavial", "gavião", "golfinho", "gorila", "gralha", 
    "grilo", "guaxinim", "hamster", "harpia", "hidra", "hiena", "homem", "hipopótamo", "iaque", "ibis", "iguana", 
    "impala", "inseto", "jaburu", "jabuti", "jacaré", "jacu", "jaguar", "jaguatirica", "jararaca", "javali", 
    "jibóia", "joaninha", "joão de barro", "jumento", "lacraia", "lagarta", "lagartixa", "lagosta", "lagostim", 
    "leão", "leoa", "lêmure", "lesma", "lhama", "ligre", "linguado", "lobo", "lobo cinzento", "lobo guará", 
    "lontra", "louva a deus", "lula", "macaco", "mamute", "marreco", "marimbondo", "mariposa", "marisco", 
    "maritaca", "medusa", "morcego", "mosca", "mosquito", "mico", "minhoca", "mula", "naja", "namorado", "narval", 
    "Nautilus", "onça", "orangotango", "ornitorrinco", "ostra", "ourico", "ovelha", "paca", "panda", "pantera", 
    "papagaio", "papa mosca", "pardal", "passarinho", "pato", "pavão", "peixe", "peixe boi", "percevejo", 
    "perereca", "periquito", "peru", "pica pau", "Pintassilgo", "píton", "planária", "polvo", "pombo", "pônei", 
    "porco", "porco espinho", "porquinho da índia", "quati", "quero quero", "quati mirim", "raia", "raposa", 
    "ratazana", "rato", "rena", "rinoceronte", "rouxinol", "sabiá", "sagui", "salmão", "sanguessuga", "sanhaço", 
    "sapo", "sardinha", "serpente", "siri", "sucuri", "suricato", "tamanduá", "tamanduá bandeira", "tamanduá mirim",
    "tarântula", "tartaruga", "tatu", "tatuí", "tênia", "tentilhão", "tigre", "tilápia", "touro", "traíra", 
    "tubarão", "tucano", "tuim", "tuiuiú", "urso branco", "urso pardo", "urso panda", "urso panda vermelho",
    "urubu ", "vaca ", "vaga lume", "veado", "verme", "vespa", "zangão", "zebra", "zebu"
]

export default animais