const nba = [
    "lebron james", "anthony Davis", "Austin Reeves", "Lakers", "Giannis Antetokounmpo", "Krhis Middleton",
    "Jrue Holiday", "Brook Lopez", "Bobby Portis Jr", "Bucks", "Jayson Tatum", "Jaylen Brown", "Al Horford",
    "Derrick White", "Malcolm Brogdon", "Blake Griffin", "Marcus Smart", "Robert Williams", "Celtics", 
    "Joel Embiid", "James Harden", "Tyrese Maxey", "Tobias Harris", "P J Tucker", "Donovan Mitchell",
    "Darius Garland", "Jarret Allen", "Evan Mobley", "Cavaliers", "Jalen Brunson", "Julius Randle", "RJ Barret",
    "Derrick Rose", "Knicks", "Mikal Bridges", "Ben Simmons", "Spencer Dinwiddie", "Seth Curry", "Joe Harris",
    "Nets", "Tare Young", "Dejoun Murray", "Clint Capela", "John Collins", "Bogdan Bogdanovic", "Saddiq Bey",
    "Hawks", "Jimmy Butler", "Tyler Hero", "Bam Adebayo", "Kevin Love", "Kyle Lowry", "Max Strus", "Heat",
    "Pascal Siakam", "Fred VanVleet", "Scottie Barnes", "Gary Trent JR", "OG Anunoby", "Raptyors", 
    "Demar DeRozan", "Zach Lavine", "Lonzo Ball", "Nikola Vucevic", "Alex Caruso", "patrick Beverley",
    "Bulls", "Tyrese Haliburton", "Myles Turner", "Bennedict Mathurin", "Buddy Hield", "George Hill", "Pacers",
    "Kyle Kuzma", "Bradley Beal", "Kristaps Porzingis", "Wizards", "Paolo Banchero", "Bol Bol", "Franz Wagner",
    "Markelle Fultz", "Jalen Suggs", "Magic", "Lamelo Ball", "Kelly Oubre JR", "Gordon Hayward", "Terry Rozier",
    "PJ Washington", "Dennis Smith JR", "Hornets", "James Wiseman", "Cade Cunningham", "Bojan Bogdanovic",
    "Pistons", "Nikola Jokic", "Jamal Murray", "Michael Porter JR", "Aaron Gordon", "Bruce Brown", "Nuggets",
    "Ja Morant", "Dillon Brooks", "Desmond Bane", "Steve Adams", "Jaren Jackson Jr", "Grizzlies", "Damantas Sabonis",
    "Malik Monk", "Harrison Barnes", "Kevin Huerter", "DeAaron Fox", "Kings", "Kevin Durant", "Devin Booker",
    "Chris Paul", "Deandre Ayton", "Cameron Payne", "Damion Lee", "Suns", "Russel Westbrook", "Kawhi Leonard", 
    "Paul George", "Eric Gordon", "Ivica Zubac", "Marcus Morris", "Terance Mann", "Nicolas Batum", "Clippers", 
    "Stephen Curry", "Klay Thompson", "Jordan Poole", "Andrew Wiggins", "Draymond Green", "Kevon Looney", 
    "Gary Payton", "Andre Iguodala", "Warriors", "Dennis Schroder", "DAngelo Russel", "Antohny Edwards", 
    "Karl Anthony Towns", "Rudy Gobert", "Mike Conley Jr", "Timberwolves", "Zion Williamson", "Brandon Ingram", 
    "C J McCollum", "Jonas Valanciunas", "Jose Alvarado", "Pelicans", "Shai Gilgeous Alexander", "Josh Giddey", 
    "Chet Holmgren", "Luka Doncic", "Kyrie Irving", "Christian Wood", "Tim Hardaway JR", "Reggie Bullock", 
    "Dwight Powell", "Maxi Kleber", "Mavericks", "Lauri Markkanen", "Jordan Clarkson", "Jazz", "Damian Lillard", 
    "Jerami Grant", "Jusuf Nurkic", "Cam Reddish", "Blazers", "Jalen Green", "Rockets", "Keldon Johnson", 
    "Tre Jones", "Devin Vassel", "Spurs", "Lary Bird", "Michael Jordan", "Kobe Bryant", "Bill Russel", "Supersonics",
    "kareem abdul jabbar", "Dwayne Wade", "dirk nowitzki", "Steve Nash", "Steve Kerr", "Shaq", "Charles Barkley",
    "Magic Johnson", "Karl Malone", "Scottie Pippen", "Wilt Chamberlain", "Dennis Rodman", "Allen Iverson",
    "Pau Gasol", "Tim Duncan", "Tony Parker", "Carmelo Anthony", "DeMarcus Cousins", "Ray Allen", "Reggie Miller"
]

export default nba